tinyMCE.addI18n('ja.concrete',{
style_select:"スタイル",
font_size:"フォントサイズ",
fontdefault:"フォント",
block:"フォーマット",
paragraph:"段落",
div:"Div",
address:"住所",
pre:"整形済み",
h1:"見出し1",
h2:"見出し2",
h3:"見出し3",
h4:"見出し4",
h5:"見出し5",
h6:"見出し6",
blockquote:"引用",
code:"ソースコード",
samp:"コードサンプル",
dt:"語句定義",
dd:"語句説明",
bold_desc:"太字 (Ctrl+B)",
italic_desc:"斜体 (Ctrl+I)",
underline_desc:"下線 (Ctrl+U)",
striketrough_desc:"打消し線",
justifyleft_desc:"左揃え",
justifycenter_desc:"中央揃え",
justifyright_desc:"右揃え",
justifyfull_desc:"均等割付",
bullist_desc:"番号なしリスト",
numlist_desc:"番号つきリスト",
outdent_desc:"インデント解除",
indent_desc:"インデント",
undo_desc:"元に戻す (Ctrl+Z)",
redo_desc:"やり直す (Ctrl+Y)",
link_desc:"リンクの挿入/編集",
unlink_desc:"リンク解除",
image_desc:"画像の挿入/編集",
cleanup_desc:"コード整形",
code_desc:"HTMLソース編集",
sub_desc:"下付き",
sup_desc:"上付き",
hr_desc:"水平線",
removeformat_desc:"フォーマット解除",
custom1_desc:"説明文を入力してください。",
forecolor_desc:"文字色",
backcolor_desc:"背景色",
charmap_desc:"特殊文字",
visualaid_desc:"ガイドラインと非表示項目の表示切替",
anchor_desc:"アンカーの挿入/編集",
cut_desc:"切り取り",
copy_desc:"コピー",
paste_desc:"貼り付け",
image_props_desc:"画像のプロパティ",
newdocument_desc:"新規作成",
help_desc:"ヘルプ",
blockquote_desc:"引用",
clipboard_msg:"このコマンドはFirefoxでは使用できません。",
path:"パス",
newdocument:"編集中のデータを破棄してもよろしいですか？",
toolbar_focus:"ツールボタンへジャンプ - Alt+Q, エディタにジャンプ - Alt-Z, エレメントパスへジャンプ - Alt-X",
more_colors:"その他の色"
});